language: cpp
dist: trusty
sudo: required
cache: ccache
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval "${MATRIX_EVAL}"; fi
- PATH=$PATH:$HOME/bin
install: travis/install_deps.sh
script: travis/compile.sh
env:
  matrix:
    - PLATFORM="native_static"
    - PLATFORM="native_dyn"
    - PLATFORM="win32_static"
    - PLATFORM="win32_dyn"
    - PLATFORM="android_arm"
    - PLATFORM="android_arm64"

addons:
  apt:
    packages:
      - cmake
      - python3.5
      - python3-pip
      - libbz2-dev
      - ccache
      - zlib1g-dev
      - uuid-dev
      - cython3
      - g++-mingw-w64-i686
      - gcc-mingw-w64-i686
      - gcc-mingw-w64-base
      - mingw-w64-tools
      - gcovr

matrix:
  include:
    - env: PLATFORM="native_dyn"
      os: osx
